In [ ]:
#what is machine learning??
#numpy #pandas

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4])
v2 = np.array([6,5,4,7])

In [3]:
print(v1+v2)

[ 7  7  7 11]


In [4]:
v1

array([1, 2, 3, 4])

In [5]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[9,10,7],[8,9,7]])

In [6]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
m2

array([[ 9, 10,  7],
       [ 8,  9,  7]])

In [8]:
print(m1+m2)

[[10 12 10]
 [12 14 13]]


# matrix multiplication

In [18]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[9,10],[8,9],[5,1]])
print(m1)
print()
print(m2)
print()
r=np.dot(m1,m2)
print(r)      #1*9 + 2*8 + 3*5  = 9+16+15 =40

[[1 2 3]
 [4 5 6]]

[[ 9 10]
 [ 8  9]
 [ 5  1]]

[[ 40  31]
 [106  91]]


In [10]:
# matrix addition
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[9,10,7],[8,9,7]])
print(m1+m1)
print()
print(m2-m1)

[[ 2  4  6]
 [ 8 10 12]]

[[8 8 4]
 [4 4 1]]


# change the row vector into column vector

In [11]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
a.reshape(3,1)    #(3,1) is (row,colunm)

array([[1],
       [2],
       [3]])

# TRANSPOSE

In [13]:
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'